# theme: jekyll-theme-slate
remote_theme: thelehhman/texture
theme: texture


texture:
  title: Young Woo, Ju
  tagline: A Boy
  date_format: "%b %-d, %Y"

  social_links:
    github:  whoareyouwhoami
    