---
title: "Tesseract 학습시키기"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

이 문서는 Tesseract 4.00을 학습시키는 과정을 알아보겠다. 학습을 위해 Ubuntu 18.04 운영체제를 사용했다. 학습에 사용될 데이터는 [AI Hub](http://www.aihub.or.kr/)에서 제공하는 한국어 글자체 이미지 데이터를 사용했다. Tesseract 학습에 자세한 내용은 [여기](https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00#tutorial-guide-to-lstmtraining)를 확인하면 된다.  


### 학습 옵션

**1. 튜닝 (Fine tune)**  
**2. 레이어 교체**  
**3. 새로 학습 시키기**


### 학습 절차  
[tesstutorial](https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00#tesstutorial)을 보면 바로 `tesstrain.sh` 스크립트를 실행시키면 학습에 필요한 데이터들을 만들어 주어서 글꼴만 있으면 바로 학습이 가능하다. 그 외에도 [tesstrain](https://github.com/tesseract-ocr/tesstrain) 레포를 보면 이미지를 사용한 학습을 볼 수 있다.

<br>

그럼 학습 절차가 어떻게 되는지 알아보겠다. 

1. 학습을 위해서는 `<lang>.<font>.<exp>.tif`의 이미지 파일이 필요하다. 여기서 `<lang>`은 언어, `<font>`는 글꼴 그리고 `<exp>`는 순서를 지정해주면 된다. **(예시: `kor.font1.exp0.tif`, `kor.font1.exp1.tif`, `kor.font2.exp0.tif`)**

2. `.box` 파일을 만들어 준다. 이 파일 안에는 단어/문장이 있는 위치가 있다. Tesseract 3에서는 각 단어의 박스값들이 필요했지만 Tesseract 4 이후 부터는 각 문장의 박스값만 필요하다. 만약 다수의 문장들이 있으면 박스 파일 안에 새줄이라고 표현해 주어야 한다.

3. `unicharset` 파일을 만들어야 한다. 이 파일에는 이미지에 있는 중복된 단어들을 제외한 파일들이다.  
    - **문장** : 안녕하세요. 안녕히 가세요.
    - **unicharset** : 안, 녕, 하, 히, 가, 세, 요  

4. 위에 파일들을 다 만들면 학습에 필요한 `.lstmf` 파일을 만든다.



### 설치 가이드

**1. Ubuntu 18.04에는 `Leptonica` 패키지가 설치되어 있을 것이다. 안되어 있다면 아래 코드를 통해 설치하면 된다.**

```
$ sudo apt-get install libleptonica-dev
```


**2. Tesseract을 설치하고 학습에 필요한 패키지들을 설치한다.**

```
# Tesseract 설치
$ sudo apt install tesseract-ocr
$ sudo apt install libtesseract-dev


# 학습에 필요한 패키지 설치
$ sudo apt-get install libicu-dev libpango1.0-dev libcairo2-dev
$ sudo apt-get install g++ autoconf automake libtool pkg-config libpng-dev libjpeg8-dev libtiff5-dev zlib1g-dev
```  




<br>

### 기타  

**한국어 설치**  

한국어 설치를 위해서는 먼서 `tessdata` 폴더로 이동해야 된다.

```
# 3곳 중 한 곳에 있을꺼다
$ cd /usr/share/tesseract-ocr/tessdata
$ cd /usr/share/tessdata
$ cd /usr/share/tesseract-ocr/4.00

```

폴더로 이동 후 아래 코드를 실행시켜 한국어를 설치한다.  

```
$ sudo wget https://github.com/tesseract-ocr/tessdata/raw/4.00/kor.traineddata
```


